[package]
name = "steam_info"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.66"
raw-window-handle = "0.5.0"

[dependencies.linapi]
path = "../linapi"
default-features = false

[dependencies.glutin]
version = "0.30.0"
default-features = false
features = [
    #
    "glx",
]

[dependencies.winit]
version = "0.27.5"
default-features = false
features = [
    #
    "x11",
]

[build-dependencies]
gl_generator = "0.14.0"
